# Generated by Django 2.2.4 on 2019-09-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('craftDB', '0002_machine_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftingRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='craftDB.Recipe')),
            ],
            bases=('craftDB.recipe',),
        ),
        migrations.CreateModel(
            name='Slotdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('slot', models.IntegerField(default=1, verbose_name='Slot')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'craftDB'), ('model', 'OreDict')), models.Q(('app_label', 'craftDB'), ('model', 'Item')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.CraftingRecipe')),
            ],
            options={
                'verbose_name': 'Slot Data',
                'verbose_name_plural': 'Slot Data',
            },
        ),
        migrations.CreateModel(
            name='ModPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('mods', models.ManyToManyField(blank=True, to='craftDB.Mod', verbose_name='Mods')),
            ],
        ),
        migrations.CreateModel(
            name='MachineRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='craftDB.Recipe')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Machine', verbose_name='Machine')),
            ],
            bases=('craftDB.recipe',),
        ),
        migrations.CreateModel(
            name='MachineInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'craftDB'), ('model', 'OreDict')), models.Q(('app_label', 'craftDB'), ('model', 'Item')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.MachineRecipe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('items', models.ManyToManyField(blank=True, to='craftDB.Item', verbose_name='Items')),
            ],
        ),
        migrations.CreateModel(
            name='ByProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Item', verbose_name='Byproduct')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftDB.Recipe')),
            ],
            options={
                'verbose_name': 'Byproduct',
                'verbose_name_plural': 'Byproducts',
            },
        ),
    ]
