# Generated by Django 2.2.4 on 2019-09-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0003_byproducts_craftingrecipe_group_machineinput_machinerecipe_modpack_slotdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod',
            old_name='abbrevations',
            new_name='abbreviations',
        ),
    ]
