# Generated by Django 2.2.4 on 2019-09-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0005_auto_20190909_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preferred',
            field=models.BooleanField(default=False, verbose_name='Preferred Recipe'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sprite',
            field=models.ImageField(default='/sprites/default.jpg', upload_to='sprites/'),
        ),
        migrations.RemoveField(
            model_name='mod',
            name='overwriting_mod',
        ),
        migrations.AddField(
            model_name='mod',
            name='overwriting_mod',
            field=models.ManyToManyField(blank=True, null=True, related_name='_mod_overwriting_mod_+', to='craftDB.Mod', verbose_name='Overwritten By'),
        ),
    ]
