# Generated by Django 2.2.4 on 2019-09-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0006_auto_20190915_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='overwriting_mod',
        ),
        migrations.AddField(
            model_name='mod',
            name='overwriting_mods',
            field=models.ManyToManyField(blank=True, null=True, related_name='_mod_overwriting_mods_+', to='craftDB.Mod', verbose_name='Overwritten By'),
        ),
    ]
