# Generated by Django 2.2.4 on 2019-09-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0007_auto_20190915_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sprite',
            field=models.ImageField(default='default.jpg', upload_to='sprites/'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='overwriting_mods',
            field=models.ManyToManyField(blank=True, related_name='_mod_overwriting_mods_+', to='craftDB.Mod', verbose_name='Overwritten By'),
        ),
    ]
