# Generated by Django 2.2.4 on 2019-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0008_auto_20190915_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='byproducts',
            name='chance',
            field=models.IntegerField(default=100, verbose_name='% Chance'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(default='', verbose_name='Template'),
            preserve_default=False,
        ),
    ]
