# Generated by Django 2.2.4 on 2019-09-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftDB', '0009_auto_20190916_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sprite',
            field=models.ImageField(default='sprites/default.jpg', upload_to='sprites/'),
        ),
    ]
